<?php namespace App\Validata\Handlers\Repositories;

use App\Validata\Handlers\ValidataSearchInterface;
use DB;

class ValidataSearchRepository implements ValidataSearchInterface
{
	public function get($documents = []) {
		$querySearch = [];

		$querySearch[] = "
			SELECT 'PERSONAL' AS 'TAB',
		       re.documento AS 'DOCUMENTO',
		       re.apellido_pat AS 'PATERNO',
		       re.apellido_mat AS 'MATERNO',
		       re.nombre AS 'NOMBRES',
		       re.fec_nac AS 'NACIMIENTO',
		       '' AS 'TELEFONO',
		       '' AS 'TIPO TELEFONO',
		       '' AS 'ORIGEN DATA',
		       '' AS 'FECHA DATA',
		       UPPER(re.direccion) AS 'DIRECCION',
		       UPPER(re.ubigeo_dir) AS 'UBIGEO',
		       '' AS 'PERIODO',
		       '' AS 'RUC',
		       '' AS 'EMPRESA',
		       '' AS 'SUELDO',
		       '' AS 'SITUACION',
		       '' AS 'DOCUMENTO_FAMILIAR',
		       '' AS 'NACIMIENTO_FAMILIAR',
		       '' AS 'NOMBRES_FAMILIAR',
		       '' AS 'RELACION_FAMILIAR',
		       '' AS 'CORREO',
		       '' AS 'FECHA_REPORTE',
		       '' AS 'CANTIDAD_EMPRESAS',
		       '' AS 'CALIFICACION_NORMAL',
		       '' AS 'CALIFICACION_CPP',
		       '' AS 'CALIFICACION_DEFICIENTE',
		       '' AS 'CALIFICACION_DUDOSO',
		       '' AS 'CALIFICACION_PERDIDA',
		       '' AS 'NOMBRE_COMPLETO_UNO',
		       '' AS 'DOCUMENTO_DOS',
		       '' AS 'NOMBRECOMPLETO_DOS',
		       '' AS 'CLASE',
		       '' AS 'COMPRA',
		       '' AS 'FABRICACION',
		       '' AS 'MARCA',
		       '' AS 'PLACA',
		       '' AS 'NRO_TRANSFERENCIA',
		       '' AS 'TIPO_PROPIEDAD',
		       '' AS 'RAZON_SOCIAL',
		       '' AS 'NOMBRE_COMERCIAL',
		       '' AS 'TIPO_EMPRESA',
		       '' AS 'FECHA_INSCRIPCION',
		       '' AS 'ESTADO',
		       '' AS 'FECHA_BAJA',
		       '' AS 'CONDICION',
		       '' AS 'TIPO_CONTRIBUYENTE',
		       '' AS 'GIRO' 
			FROM reniec_2018 AS re
				WHERE re.documento IN (".implode(',', $documents).")";

		$querySearch[] = "
			SELECT 'PERSONAL' AS 'TAB',
		       '' AS 'DOCUMENTO',
		       IFNULL(CONVERT(emp.provincia USING utf8), '') AS 'PATERNO',
		       IFNULL(CONVERT(emp.distrito USING utf8), '') AS 'MATERNO',
		       IFNULL(CONVERT(emp.departamento USING utf8), '') AS 'NOMBRES',
		       '' AS 'NACIMIENTO',
		       '' AS 'TELEFONO',
		       '' AS 'TIPO TELEFONO',
		       '' AS 'ORIGEN DATA',
		       '' AS 'FECHA DATA',
		       IFNULL(CONVERT(emp.direccion USING utf8), '') AS 'DIRECCION',
		       IFNULL(CONVERT(emp.ubigeo USING utf8), '') AS 'UBIGEO',
		       '' AS 'PERIODO',
		       IFNULL(emp.ruc COLLATE utf8_unicode_ci, '') AS 'RUC',
		       '' AS 'EMPRESA',
		       '' AS 'SUELDO',
		       '' AS 'SITUACION',
		       '' AS 'DOCUMENTO_FAMILIAR',
		       '' AS 'NACIMIENTO_FAMILIAR',
		       '' AS 'NOMBRES_FAMILIAR',
		       '' AS 'RELACION_FAMILIAR',
		       '' AS 'CORREO',
		       '' AS 'FECHA_REPORTE',
		       '' AS 'CANTIDAD_EMPRESAS',
		       '' AS 'CALIFICACION_NORMAL',
		       '' AS 'CALIFICACION_CPP',
		       '' AS 'CALIFICACION_DEFICIENTE',
		       '' AS 'CALIFICACION_DUDOSO',
		       '' AS 'CALIFICACION_PERDIDA',
		       '' AS 'NOMBRE_COMPLETO_UNO',
		       '' AS 'DOCUMENTO_DOS',
		       '' AS 'NOMBRECOMPLETO_DOS',
		       '' AS 'CLASE',
		       '' AS 'COMPRA',
		       '' AS 'FABRICACION',
		       '' AS 'MARCA',
		       '' AS 'PLACA',
		       '' AS 'NRO_TRANSFERENCIA',
		       '' AS 'TIPO_PROPIEDAD',
		       IFNULL(emp.razonsocial COLLATE utf8_unicode_ci, '') AS 'RAZON_SOCIAL',
		       '' AS 'NOMBRE_COMERCIAL',
		       '' AS 'TIPO_EMPRESA',
		       '' AS 'FECHA_INSCRIPCION',
		       IFNULL(emp.estado COLLATE utf8_unicode_ci, '') AS 'ESTADO',
		       '' AS 'FECHA_BAJA',
		       '' AS 'CONDICION',
		       '' AS 'TIPO_CONTRIBUYENTE',
		       IFNULL(emp.giro COLLATE utf8_unicode_ci, '') AS 'GIRO' 
			FROM empresa AS emp
				WHERE emp.ruc IN (".implode(',', $documents).")";

		$querySearch[] = "
			SELECT 'TELEFONOS' AS 'TAB',
			    tel2.*
			FROM
			  	(SELECT tel.*,
			        vpp.source_date AS 'FECHA DATA',
			        '' AS 'DIRECCION',
			        '' AS 'UBIGEO',
			        '' AS 'PERIODO',
			        '' AS 'RUC',
			        '' AS 'EMPRESA',
			        '' AS 'SUELDO',
			        '' AS 'SITUACION',
			        '' AS 'DOCUMENTO_FAMILIAR',
		       		'' AS 'NACIMIENTO_FAMILIAR',
		       		'' AS 'NOMBRES_FAMILIAR',
		       		'' AS 'RELACION_FAMILIAR',
		       		'' AS 'CORREO',
		       		'' AS 'FECHA_REPORTE',
		       		'' AS 'CANTIDAD_EMPRESAS',
		       		'' AS 'CALIFICACION_NORMAL',
		       		'' AS 'CALIFICACION_CPP',
		       		'' AS 'CALIFICACION_DEFICIENTE',
		       		'' AS 'CALIFICACION_DUDOSO',
		       		'' AS 'CALIFICACION_PERDIDA',
		       		'' AS 'NOMBRE_COMPLETO_UNO',
			       	'' AS 'DOCUMENTO_DOS',
			       	'' AS 'NOMBRECOMPLETO_DOS',
			       	'' AS 'CLASE',
			       	'' AS 'COMPRA',
			       	'' AS 'FABRICACION',
			       	'' AS 'MARCA',
			       	'' AS 'PLACA',
			       	'' AS 'NRO_TRANSFERENCIA',
			       	'' AS 'TIPO_PROPIEDAD',
			       	'' AS 'RAZON_SOCIAL',
		       		'' AS 'NOMBRE_COMERCIAL',
		       		'' AS 'TIPO_EMPRESA',
		       		'' AS 'FECHA_INSCRIPCION',
		       		'' AS 'ESTADO',
		       		'' AS 'FECHA_BAJA',
		       		'' AS 'CONDICION',
		       		'' AS 'TIPO_CONTRIBUYENTE',
		       		'' AS 'GIRO'
			   	FROM
			     	(
			     		SELECT 
			     			mov.documento AS 'DOCUMENTO',
				            '' AS 'PATERNO',
				            '' AS 'MATERNO',
				            '' AS 'NOMBRES',
				            '' AS 'NACIMIENTO',
				            mov.numero AS 'TELEFONO',
				            'CELULAR' AS 'TIPO TELEFONO',
				            'MOVISTAR' AS 'ORIGEN DATA'
				      	FROM movistar AS mov
				      		WHERE mov.documento IN (".implode(',', $documents).")
			      		UNION ALL 
			      		SELECT 
			      			cla.documento AS 'DOCUMENTO',
			                '' AS 'PATERNO',
			                '' AS 'MATERNO',
			                '' AS 'NOMBRES',
			                '' AS 'NACIMIENTO',
			                cla.numero AS 'TELEFONO',
			                'CELULAR' AS 'TIPO TELEFONO',
			                'CLARO' AS 'ORIGEN DATA'
			      		FROM claro AS cla
			      			WHERE cla.documento IN (".implode(',', $documents).")
			      		UNION ALL
			      		SELECT 
			      			ent.documento AS 'DOCUMENTO',
			                '' AS 'PATERNO',
			                '' AS 'MATERNO',
			                '' AS 'NOMBRES',
			                '' AS 'NACIMIENTO',
			                ent.numero AS 'TELEFONO',
			                'CELULAR' AS 'TIPO TELEFONO',
			                'ENTEL' AS 'ORIGEN DATA'
			      		FROM entel AS ent
			      			WHERE ent.documento IN (".implode(',', $documents).")
			      		UNION ALL
			      		SELECT 
			      			bit.documento AS 'DOCUMENTO',
			                '' AS 'PATERNO',
			                '' AS 'MATERNO',
			                '' AS 'NOMBRES',
			                '' AS 'NACIMIENTO',
			                bit.numero AS 'TELEFONO',
			                'CELULAR' AS 'TIPO TELEFONO',
			                'BITEL' AS 'ORIGEN DATA'
			      		FROM bitel AS bit
			      			WHERE bit.documento IN (".implode(',', $documents).")
			      		UNION ALL
			      		SELECT 
			      			movfi.documento AS 'DOCUMENTO',
			                '' AS 'PATERNO',
			                '' AS 'MATERNO',
			                '' AS 'NOMBRES',
			                '' AS 'NACIMIENTO',
			                movfi.numero AS 'TELEFONO',
			                'TELEFONO FIJO' AS 'TIPO TELEFONO',
			                'MOVISTAR_FIJO' AS 'ORIGEN DATA'
			      		FROM movistar_fijo AS movfi
			      			WHERE movfi.documento IN (".implode(',', $documents).")
			      		UNION ALL
			      		SELECT
			      			emptel.ruc COLLATE utf8_unicode_ci AS 'DOCUMENTO',
			      			'' AS 'PATERNO',
			      			'' AS 'MATERNO',
			      			'' AS 'NOMBRES',
			      			'' AS 'NACIMIENTO',
			      			emptel.numero AS 'TELEFONO',
			      			UPPER(emptel.tipo) AS 'TIPO TELEFONO',
			      			UPPER(emptel.fuente) AS 'ORIGEN DATA'
			      		FROM empresa_telefono AS emptel
		      				WHERE emptel.ruc IN (".implode(',', $documents).")
		      				AND emptel.fuente NOT IN ('CLARO', 'MOVISTAR')
			      	) AS tel
			   LEFT JOIN validata_people AS vp ON vp.document = tel.DOCUMENTO
			   LEFT JOIN validata_people_phones AS vpp ON (vpp.validata_people_id = vp.id AND vpp.phone = tel.TELEFONO)) AS tel2 ";
		$querySearch[] = "
			SELECT 'FAMILIARES' AS 'TAB',
				fam2.DOCUMENTO AS 'DOCUMENTO',
				IFNULL(CONVERT(fam2.PATERNO USING utf8), '') AS 'PATERNO',
			    IFNULL(CONVERT(fam2.MATERNO USING utf8), '') AS 'MATERNO',
			    IFNULL(CONVERT(fam2.NOMBRES USING utf8), '') AS 'NOMBRES',
			    '' AS 'NACIMIENTO',
			    '' AS 'TELEFONO',
			    '' AS 'TIPO TELEFONO',
			    '' AS 'ORIGEN DATA',
			    '' AS 'FECHA DATA',
			    '' AS 'DIRECCION',
			    '' AS 'UBIGEO',
			    '' AS 'PERIODO',
			    '' AS 'RUC',
			    '' AS 'EMPRESA',
			    '' AS 'SUELDO',
			    '' AS 'SITUACION',
			    CONVERT(fam2.DOCUMENTO_FAMILIAR USING utf8) AS 'DOCUMENTO_FAMILIAR',
			    fam2.NACIMIENTO_FAMILIAR AS 'NACIMIENTO_FAMILIAR',
			    CONVERT(fam2.NOMBRES_FAMILIAR USING utf8) AS 'NOMBRES_FAMILIAR',
			    CONVERT(fam2.RELACION USING utf8) AS 'RELACION_FAMILIAR',
			    '' AS 'CORREO',
			    '' AS 'FECHA_REPORTE',
		       	'' AS 'CANTIDAD_EMPRESAS',
		       	'' AS 'CALIFICACION_NORMAL',
		       	'' AS 'CALIFICACION_CPP',
		       	'' AS 'CALIFICACION_DEFICIENTE',
		       	'' AS 'CALIFICACION_DUDOSO',
		       	'' AS 'CALIFICACION_PERDIDA',
		       	'' AS 'NOMBRE_COMPLETO_UNO',
		       	'' AS 'DOCUMENTO_DOS',
		       	'' AS 'NOMBRECOMPLETO_DOS',
		       	'' AS 'CLASE',
		       	'' AS 'COMPRA',
		       	'' AS 'FABRICACION',
		       	'' AS 'MARCA',
		       	'' AS 'PLACA',
		       	'' AS 'NRO_TRANSFERENCIA',
		       	'' AS 'TIPO_PROPIEDAD',
		       	'' AS 'RAZON_SOCIAL',
		       	'' AS 'NOMBRE_COMERCIAL',
		       	'' AS 'TIPO_EMPRESA',
		       	'' AS 'FECHA_INSCRIPCION',
		       	'' AS 'ESTADO',
		       	'' AS 'FECHA_BAJA',
		       	'' AS 'CONDICION',
		       	'' AS 'TIPO_CONTRIBUYENTE',
		       	'' AS 'GIRO'
			FROM
			  	(SELECT 
			  		fam.DOCUMENTO_PARENT AS 'DOCUMENTO',
			  		IFNULL(UPPER(vp.last_name), IFNULL(reniec.apellido_pat COLLATE utf8_unicode_ci, '')) AS 'PATERNO',
				    IFNULL(UPPER(vp.surname), IFNULL(reniec.apellido_mat COLLATE utf8_unicode_ci, '')) AS 'MATERNO',
				    IFNULL(UPPER(vp.names), IFNULL(reniec.nombre COLLATE utf8_unicode_ci, '')) AS 'NOMBRES',
			  		fam.DOCUMENTO AS 'DOCUMENTO_FAMILIAR',
			  		IF(fam.RELACION != vpr.relation_type COLLATE utf8_unicode_ci, vpr.relation_type, IFNULL(fam.RELACION COLLATE utf8_unicode_ci, vpr.relation_type)) AS 'RELACION',
			  		IFNULL(vpr.birth, '') AS 'NACIMIENTO_FAMILIAR',
			  		fam.NOMBRES_FAMILIAR AS 'NOMBRES_FAMILIAR'
			   	FROM
			     	(
			     		SELECT 
			     			refa.documento AS 'DOCUMENTO',
				            UPPER(refa.nombre) AS 'NOMBRES_FAMILIAR',
				            'HIJO' AS 'RELACION',
				            refa.doc_parent AS 'DOCUMENTO_PARENT'
				      	FROM reniec_familiares AS refa
				      		WHERE refa.doc_parent IN (".implode(',', $documents).")
				      	UNION ALL
				      	SELECT 
			     			reh.documento AS 'DOCUMENTO',
				            UPPER(reh.nombre) AS 'NOMBRES_FAMILIAR',
				            'HERMANO' AS 'RELACION',
				            reh.doc_parent AS 'DOCUMENTO_PARENT'
				      	FROM reniec_hermanos AS reh
				      		WHERE reh.doc_parent IN (".implode(',', $documents).")
				      	UNION ALL
				      	SELECT 
			     			rec.documento AS 'DOCUMENTO',
				            UPPER(rec.nombre) AS 'NOMBRES_FAMILIAR',
				            rec.parentezco AS 'RELACION',
				            rec.doc_parent AS 'DOCUMENTO_PARENT'
				      	FROM reniec_conyuges AS rec
				      		WHERE rec.doc_parent IN (".implode(',', $documents).")
			      	) AS fam
			   	LEFT JOIN validata_people AS vp ON vp.document = fam.DOCUMENTO_PARENT
			   	LEFT JOIN validata_people_relatives AS vpr ON (vpr.validata_people_id = vp.id AND vpr.document = fam.DOCUMENTO)
				LEFT JOIN reniec_2018 AS reniec ON reniec.documento = fam.DOCUMENTO_PARENT) AS fam2 ";
		$querySearch[] = "
			SELECT 'ESSALUD' AS 'TAB',
			    ess.documento AS 'DOCUMENTO',
			    '' AS 'PATERNO',
			    '' AS 'MATERNO',
			    '' AS 'NOMBRES',
			    '' AS 'NACIMIENTO',
			    '' AS 'TELEFONO',
			    '' AS 'TIPO TELEFONO',
			    '' AS 'ORIGEN DATA',
			    '' AS 'FECHA DATA',
			    '' AS 'DIRECCION',
			    '' AS 'UBIGEO',
			    ess.periodo AS 'PERIODO',
			    ess.ruc AS 'RUC',
			    ess.empresa AS 'EMPRESA',
			    ess.sueldo AS 'SUELDO',
			    ess.condicion AS 'SITUACION',
			    '' AS 'DOCUMENTO_FAMILIAR',
		       	'' AS 'NACIMIENTO_FAMILIAR',
		       	'' AS 'NOMBRES_FAMILIAR',
		       	'' AS 'RELACION_FAMILIAR',
		       	'' AS 'CORREO',
		       	'' AS 'FECHA_REPORTE',
		       	'' AS 'CANTIDAD_EMPRESAS',
		       	'' AS 'CALIFICACION_NORMAL',
		       	'' AS 'CALIFICACION_CPP',
		       	'' AS 'CALIFICACION_DEFICIENTE',
		       	'' AS 'CALIFICACION_DUDOSO',
		       	'' AS 'CALIFICACION_PERDIDA',
		       	'' AS 'NOMBRE_COMPLETO_UNO',
		       	'' AS 'DOCUMENTO_DOS',
		       	'' AS 'NOMBRECOMPLETO_DOS',
		       	'' AS 'CLASE',
		       	'' AS 'COMPRA',
		       	'' AS 'FABRICACION',
		       	'' AS 'MARCA',
		       	'' AS 'PLACA',
		       	'' AS 'NRO_TRANSFERENCIA',
		       	'' AS 'TIPO_PROPIEDAD',
		       	'' AS 'RAZON_SOCIAL',
		       	'' AS 'NOMBRE_COMERCIAL',
		       	'' AS 'TIPO_EMPRESA',
		       	'' AS 'FECHA_INSCRIPCION',
		       	'' AS 'ESTADO',
		       	'' AS 'FECHA_BAJA',
		       	'' AS 'CONDICION',
		       	'' AS 'TIPO_CONTRIBUYENTE',
		       	'' AS 'GIRO'
			FROM essalud AS ess
				WHERE ess.documento IN (".implode(',', $documents).") ";
		$querySearch[] = "
			SELECT 'CORREOS' AS 'TAB',
		       	co.documento AS 'DOCUMENTO',
		       	'' AS 'PATERNO',
		       	'' AS 'MATERNO',
		       	'' AS 'NOMBRES',
		       	'' AS 'NACIMIENTO',
		       	'' AS 'TELEFONO',
		       	'' AS 'TIPO TELEFONO',
		       	'' AS 'ORIGEN DATA',
		       	'' AS 'FECHA DATA',
		       	'' AS 'DIRECCION',
		       	'' AS 'UBIGEO',
		       	'' AS 'PERIODO',
		       	'' AS 'RUC',
		       	'' AS 'EMPRESA',
		       	'' AS 'SUELDO',
		       	'' AS 'SITUACION',
		       	'' AS 'DOCUMENTO_FAMILIAR',
		       	'' AS 'NACIMIENTO_FAMILIAR',
		       	'' AS 'NOMBRES_FAMILIAR',
		       	'' AS 'RELACION_FAMILIAR',
		       	LOWER(co.correo) AS 'CORREO',
		       	'' AS 'FECHA_REPORTE',
		       	'' AS 'CANTIDAD_EMPRESAS',
		       	'' AS 'CALIFICACION_NORMAL',
		       	'' AS 'CALIFICACION_CPP',
		       	'' AS 'CALIFICACION_DEFICIENTE',
		       	'' AS 'CALIFICACION_DUDOSO',
		       	'' AS 'CALIFICACION_PERDIDA',
		       	'' AS 'NOMBRE_COMPLETO_UNO',
		       	'' AS 'DOCUMENTO_DOS',
		       	'' AS 'NOMBRECOMPLETO_DOS',
		       	'' AS 'CLASE',
		       	'' AS 'COMPRA',
		       	'' AS 'FABRICACION',
		       	'' AS 'MARCA',
		       	'' AS 'PLACA',
		       	'' AS 'NRO_TRANSFERENCIA',
		       	'' AS 'TIPO_PROPIEDAD',
		       	'' AS 'RAZON_SOCIAL',
		       	'' AS 'NOMBRE_COMERCIAL',
		       	'' AS 'TIPO_EMPRESA',
		       	'' AS 'FECHA_INSCRIPCION',
		       	'' AS 'ESTADO',
		       	'' AS 'FECHA_BAJA',
		       	'' AS 'CONDICION',
		       	'' AS 'TIPO_CONTRIBUYENTE',
		       	'' AS 'GIRO'
			FROM correo AS co
				WHERE co.documento IN (".implode(',', $documents).") ";
		$querySearch[] = "
			SELECT 'SBS' AS 'TAB',
			    vp.document AS 'DOCUMENTO',
			    '' AS 'PATERNO',
			    '' AS 'MATERNO',
			    '' AS 'NOMBRES',
			    '' AS 'NACIMIENTO',
			    '' AS 'TELEFONO',
			    '' AS 'TIPO TELEFONO',
			    '' AS 'ORIGEN DATA',
			    '' AS 'FECHA DATA',
			    '' AS 'DIRECCION',
			    '' AS 'UBIGEO',
			    '' AS 'PERIODO',
			    '' AS 'RUC',
			    '' AS 'EMPRESA',
			    '' AS 'SUELDO',
			    '' AS 'SITUACION',
			    '' AS 'DOCUMENTO_FAMILIAR',
		       	'' AS 'NACIMIENTO_FAMILIAR',
		       	'' AS 'NOMBRES_FAMILIAR',
		       	'' AS 'RELACION_FAMILIAR',
		       	'' AS 'CORREO',
		       	vps.report_date AS 'FECHA_REPORTE',
		       	vps.company_quantity AS 'CANTIDAD_EMPRESAS',
		       	vps.normal_rating AS 'CALIFICACION_NORMAL',
		       	vps.cpp_rating AS 'CALIFICACION_CPP',
		       	vps.deficient_rating AS 'CALIFICACION_DEFICIENTE',
		       	vps.uncertain_rating AS 'CALIFICACION_DUDOSO',
		       	vps.lost_rating AS 'CALIFICACION_PERDIDA',
		       	'' AS 'NOMBRE_COMPLETO_UNO',
		       	'' AS 'DOCUMENTO_DOS',
		       	'' AS 'NOMBRECOMPLETO_DOS',
		       	'' AS 'CLASE',
		       	'' AS 'COMPRA',
		       	'' AS 'FABRICACION',
		       	'' AS 'MARCA',
		       	'' AS 'PLACA',
		       	'' AS 'NRO_TRANSFERENCIA',
		       	'' AS 'TIPO_PROPIEDAD',
		       	'' AS 'RAZON_SOCIAL',
		       	'' AS 'NOMBRE_COMERCIAL',
		       	'' AS 'TIPO_EMPRESA',
		       	'' AS 'FECHA_INSCRIPCION',
		       	'' AS 'ESTADO',
		       	'' AS 'FECHA_BAJA',
		       	'' AS 'CONDICION',
		       	'' AS 'TIPO_CONTRIBUYENTE',
		       	'' AS 'GIRO' 
			FROM validata_people AS vp
				LEFT JOIN validata_people_sbs AS vps ON vps.validata_people_id = vp.id
				WHERE vp.document IN (".implode(',', $documents).") ";

		$querySearch[] = "
			SELECT 'VEHICULOS' AS 'TAB',
		       re.documento AS 'DOCUMENTO',
		       re.apellido_pat AS 'PATERNO',
		       re.apellido_mat AS 'MATERNO',
		       re.nombre AS 'NOMBRES',
		       re.fec_nac AS 'NACIMIENTO',
		       '' AS 'TELEFONO',
		       '' AS 'TIPO TELEFONO',
		       '' AS 'ORIGEN DATA',
		       '' AS 'FECHA DATA',
		       UPPER(re.direccion) AS 'DIRECCION',
		       UPPER(re.ubigeo_dir) AS 'UBIGEO',
		       '' AS 'PERIODO',
		       '' AS 'RUC',
		       '' AS 'EMPRESA',
		       '' AS 'SUELDO',
		       '' AS 'SITUACION',
		       '' AS 'DOCUMENTO_FAMILIAR',
		       '' AS 'NACIMIENTO_FAMILIAR',
		       '' AS 'NOMBRES_FAMILIAR',
		       '' AS 'RELACION_FAMILIAR',
		       '' AS 'CORREO',
		       '' AS 'FECHA_REPORTE',
		       '' AS 'CANTIDAD_EMPRESAS',
		       '' AS 'CALIFICACION_NORMAL',
		       '' AS 'CALIFICACION_CPP',
		       '' AS 'CALIFICACION_DEFICIENTE',
		       '' AS 'CALIFICACION_DUDOSO',
		       '' AS 'CALIFICACION_PERDIDA',
		       CONCAT(re.nombre, ' ', re.apellido_pat, ' ', re.apellido_mat) AS 'NOMBRE_COMPLETO_UNO',
		       ved.segundo_documento AS 'DOCUMENTO_DOS',
		       ved.segundo_nombrecompleto AS 'NOMBRECOMPLETO_DOS',
		       ved.clase AS 'CLASE',
		       ved.compra AS 'COMPRA',
		       ved.fabricacion AS 'FABRICACION',
		       ved.marca AS 'MARCA',
		       ved.placa AS 'PLACA',
		       ved.numero_transferencia AS 'NRO_TRANSFERENCIA',
		       ved.tipo_propiedad AS 'TIPO_PROPIEDAD',
		       '' AS 'RAZON_SOCIAL',
		       '' AS 'NOMBRE_COMERCIAL',
		       '' AS 'TIPO_EMPRESA',
		       '' AS 'FECHA_INSCRIPCION',
		       '' AS 'ESTADO',
		       '' AS 'FECHA_BAJA',
		       '' AS 'CONDICION',
		       '' AS 'TIPO_CONTRIBUYENTE',
		       '' AS 'GIRO'

			FROM reniec_2018 AS re
				LEFT JOIN vehiculos_documento AS ved ON ved.documento = re.documento
				WHERE re.documento IN (".implode(',', $documents).")
				AND ved.documento IS NOT NULL";

		$querySearch[] = "
			SELECT 'SUNAT' AS 'TAB',
		       re.documento AS 'DOCUMENTO',
		       re.apellido_pat AS 'PATERNO',
		       re.apellido_mat AS 'MATERNO',
		       re.nombre AS 'NOMBRES',
		       re.fec_nac AS 'NACIMIENTO',
		       '' AS 'TELEFONO',
		       '' AS 'TIPO TELEFONO',
		       '' AS 'ORIGEN DATA',
		       '' AS 'FECHA DATA',
		       CONVERT(emd.direccion USING utf8) AS 'DIRECCION',
		       CONVERT(emd.ubigeo USING utf8) AS 'UBIGEO',
		       '' AS 'PERIODO',
		       emd.ruc AS 'RUC',
		       '' AS 'EMPRESA',
		       '' AS 'SUELDO',
		       '' AS 'SITUACION',
		       '' AS 'DOCUMENTO_FAMILIAR',
		       '' AS 'NACIMIENTO_FAMILIAR',
		       '' AS 'NOMBRES_FAMILIAR',
		       '' AS 'RELACION_FAMILIAR',
		       '' AS 'CORREO',
		       '' AS 'FECHA_REPORTE',
		       '' AS 'CANTIDAD_EMPRESAS',
		       '' AS 'CALIFICACION_NORMAL',
		       '' AS 'CALIFICACION_CPP',
		       '' AS 'CALIFICACION_DEFICIENTE',
		       '' AS 'CALIFICACION_DUDOSO',
		       '' AS 'CALIFICACION_PERDIDA',
		       '' AS 'NOMBRE_COMPLETO_UNO',
		       '' AS 'DOCUMENTO_DOS',
		       '' AS 'NOMBRECOMPLETO_DOS',
		       '' AS 'CLASE',
		       '' AS 'COMPRA',
		       '' AS 'FABRICACION',
		       '' AS 'MARCA',
		       '' AS 'PLACA',
		       '' AS 'NRO_TRANSFERENCIA',
		       '' AS 'TIPO_PROPIEDAD',
		       emd.razonsocial AS 'RAZON_SOCIAL',
		       emd.nombrecomercial AS 'NOMBRE_COMERCIAL',
		       emd.tipo AS 'TIPO_EMPRESA',
		       emd.fecha_inscripcion AS 'FECHA_INSCRIPCION',
		       emd.estado AS 'ESTADO',
		       emd.fecha_baja AS 'FECHA_BAJA',
		       emd.condicion AS 'CONDICION',
		       '' AS 'TIPO_CONTRIBUYENTE',
		       emd.giro AS 'GIRO'
			FROM reniec_2018 AS re
				LEFT JOIN empresas_documento AS emd ON emd.documento = re.documento
				WHERE re.documento IN (".implode(',', $documents).")
				AND emd.documento IS NOT NULL";

		$querySearch[] = "
			SELECT 'REPRESENTANTES' AS 'TAB',
		       emre.documento AS 'DOCUMENTO',
		       '' AS 'PATERNO',
		       '' AS 'MATERNO',
		       CONVERT(emre.nombres USING utf8) AS 'NOMBRES',
		       '' AS 'NACIMIENTO',
		       '' AS 'TELEFONO',
		       '' AS 'TIPO TELEFONO',
		       '' AS 'ORIGEN DATA',
		       '' AS 'FECHA DATA',
		       '' AS 'DIRECCION',
		       '' AS 'UBIGEO',
		       '' AS 'PERIODO',
		       emre.ruc AS 'RUC',
		       '' AS 'EMPRESA',
		       '' AS 'SUELDO',
		       CONVERT(emre.cargo USING utf8) AS 'SITUACION',
		       '' AS 'DOCUMENTO_FAMILIAR',
		       '' AS 'NACIMIENTO_FAMILIAR',
		       '' AS 'NOMBRES_FAMILIAR',
		       '' AS 'RELACION_FAMILIAR',
		       '' AS 'CORREO',
		       '' AS 'FECHA_REPORTE',
		       '' AS 'CANTIDAD_EMPRESAS',
		       '' AS 'CALIFICACION_NORMAL',
		       '' AS 'CALIFICACION_CPP',
		       '' AS 'CALIFICACION_DEFICIENTE',
		       '' AS 'CALIFICACION_DUDOSO',
		       '' AS 'CALIFICACION_PERDIDA',
		       '' AS 'NOMBRE_COMPLETO_UNO',
		       '' AS 'DOCUMENTO_DOS',
		       '' AS 'NOMBRECOMPLETO_DOS',
		       '' AS 'CLASE',
		       '' AS 'COMPRA',
		       '' AS 'FABRICACION',
		       '' AS 'MARCA',
		       '' AS 'PLACA',
		       '' AS 'NRO_TRANSFERENCIA',
		       '' AS 'TIPO_PROPIEDAD',
		       '' AS 'RAZON_SOCIAL',
		       '' AS 'NOMBRE_COMERCIAL',
		       '' AS 'TIPO_EMPRESA',
		       '' AS 'FECHA_INSCRIPCION',
		       '' AS 'ESTADO',
		       '' AS 'FECHA_BAJA',
		       '' AS 'CONDICION',
		       '' AS 'TIPO_CONTRIBUYENTE',
		       '' AS 'GIRO'
			FROM empresa_representantes AS emre
				WHERE emre.ruc IN (".implode(',', $documents).") ";
		$queryString = implode(" UNION ALL ", $querySearch);
		//echo $queryString;
		//dd("fin");
		return DB::select($queryString);
	}
}